require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Layout/SpaceAfterColon:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: consistent
RSpec/MultipleExpectations:
  Enabled: false